# Generated by Django 5.2.7 on 2025-10-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='example@example.com', max_length=200),
        ),
    ]
