# Generated by Django 5.2.7 on 2025-10-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_shippingaddress_postcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postcode',
            field=models.CharField(default='', max_length=200),
        ),
    ]
