# Generated by Django 5.1.2 on 2025-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_make_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
