# Generated by Django 5.2.7 on 2025-10-21 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_status_incomingparcel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingparcel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='incomingparcel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='incomingparcel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='incomingparcel',
            name='county',
        ),
        migrations.RemoveField(
            model_name='incomingparcel',
            name='details',
        ),
        migrations.RemoveField(
            model_name='incomingparcel',
            name='ip_id',
        ),
        migrations.RemoveField(
            model_name='incomingparcel',
            name='postcode',
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='petg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='pla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting Parcel'), ('received', 'Received'), ('processed', 'Processed')], default='awaiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='incomingparcel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ParcelMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG')], max_length=10)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='store.incomingparcel')),
            ],
            options={
                'unique_together': {('parcel', 'material')},
            },
        ),
    ]
