# Generated by Django 5.2.7 on 2025-10-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_incomingparcel_address_incomingparcel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingparcel',
            name='admin_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
