# Generated by Django 5.2.7 on 2025-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_incomingparcel_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingparcel',
            name='points_calculated',
            field=models.IntegerField(blank=True, help_text='Auto-calculated based on weight, editable by admin', null=True),
        ),
    ]
