# Generated by Django 5.2.7 on 2025-10-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_incomingparcel_points_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
