# Generated by Django 5.2.7 on 2025-10-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customer_total_points_incomingparcel_points_awarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned from Parcel'), ('REDEEMED', 'Redeemed for Discount'), ('ADJUSTED', 'Admin Adjustment')], default='EARNED', max_length=20)),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='store.customer')),
                ('related_parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.incomingparcel')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
