# Generated by Django 5.2.7 on 2025-10-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_pointtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('points_per_kg_basic', models.IntegerField(default=100, help_text='Points per kg for basic members')),
                ('points_per_kg_premium', models.IntegerField(default=120, help_text='Points per kg for premium members (20% bonus)')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parcelmaterial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parcelmaterial',
            name='plastic_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.plastictype'),
        ),
        migrations.RemoveField(
            model_name='parcelmaterial',
            name='material',
        ),
    ]
