# Generated by Django 5.2.7 on 2025-10-22 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_plastictype_alter_parcelmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelmaterial',
            name='plastic_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.plastictype'),
            preserve_default=False,
        ),
    ]
