# Generated by Django 5.2.7 on 2025-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_parcelmaterial_plastic_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_business',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EARNED', 'Earned from Parcel'), ('REDEEMED', 'Redeemed for Discount'), ('ADJUSTED', 'Manual Adjustment'), ('BONUS', 'Bonus Points')], default='EARNED', max_length=20),
        ),
    ]
