# Generated by Django 5.2.7 on 2025-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_customer_is_business_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_used',
            field=models.IntegerField(default=0),
        ),
    ]
