# Generated by Django 5.2.7 on 2025-10-23 00:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_product_created_remove_product_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='points_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
