# Generated by Django 5.2.7 on 2025-10-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_product_colour_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
