# Generated by Django 5.2.7 on 2025-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_product_colour_remove_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, help_text='e.g. Black, White, Red', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, help_text='e.g. PLA, PETG, ABS', max_length=100),
        ),
    ]
