# Generated by Django 5.2.7 on 2025-10-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_product_colour_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mailerlite_subscriber_id',
            field=models.CharField(blank=True, help_text='MailerLite subscriber ID for API operations', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False, help_text='Whether user is subscribed to newsletter'),
        ),
    ]
