# Generated by Django 5.2.7 on 2025-10-27 20:16

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_customer_mailerlite_subscriber_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Use Markdown syntax for formatting'),
        ),
    ]
