# Generated by Django 5.2.7 on 2025-10-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_blogpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('👍', 'Like'), ('❤️', 'Love'), ('🎉', 'Celebrate'), ('💡', 'Insightful'), ('🤔', 'Thinking')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='store.blogpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
