# Generated by Django 5.2.7 on 2025-10-27
from django.db import migrations

def remove_blogreaction_model(apps, schema_editor):
    # Remove the BlogReaction table if it exists
    schema_editor.execute('DROP TABLE IF EXISTS store_blogreaction;')

class Migration(migrations.Migration):
    dependencies = [
        ('store', '0034_blogreaction'),
    ]
    operations = [
        migrations.RunPython(remove_blogreaction_model),
    ]
