# Generated by Django 5.2.7 on 2025-11-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_remove_blogreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_business',
            field=models.BooleanField(default=False, help_text='Is this a business customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription_active',
            field=models.BooleanField(default=False, help_text='Is subscription currently active'),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription_type',
            field=models.CharField(blank=True, help_text="e.g., 'Monthly Subscription', 'Local Subscription', 'PAYG'", max_length=50, null=True),
        ),
    ]
