# Generated by Django 5.2.7 on 2025-11-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_customer_is_business_customer_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accepted_plastic_types',
            field=models.ManyToManyField(blank=True, help_text='Plastic types this business accepts', to='store.plastictype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_delivery_day',
            field=models.DateField(blank=True, help_text='Preferred monthly delivery day', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription_setup_complete',
            field=models.BooleanField(default=False, help_text='Has the customer completed subscription setup'),
        ),
    ]
