# Generated by Django 5.2.7 on 2025-11-03 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_customer_accepted_plastic_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='box_count',
            field=models.IntegerField(default=1, help_text='Number of boxes allowed per delivery'),
        ),
        migrations.AddField(
            model_name='customer',
            name='multi_box_enabled',
            field=models.BooleanField(default=False, help_text='Admin-approved for multiple boxes per delivery'),
        ),
        migrations.CreateModel(
            name='BusinessBoxPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.IntegerField(help_text='Box number (1, 2, 3, etc.)')),
                ('plastic_type', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG')], help_text='Plastic type for this box', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_preferences', to='store.customer')),
            ],
            options={
                'ordering': ['box_number'],
                'unique_together': {('customer', 'box_number')},
            },
        ),
    ]
