# Generated by Django 5.2.7 on 2025-11-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_customer_box_count_customer_multi_box_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessboxpreference',
            name='plastic_type',
            field=models.CharField(help_text='Plastic type for this box (e.g., PLA, PETG, ABS)', max_length=50),
        ),
    ]
