# Generated by Django 5.2.7 on 2025-11-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_update_box_preference_plastic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_subscription_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom subscription price per month (for special business deals)', max_digits=6, null=True),
        ),
    ]
