# Generated by Django 5.2.7 on 2025-11-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_blogreaction_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_cancelled',
            field=models.BooleanField(default=False, help_text='Has the subscription been cancelled'),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription_end_date',
            field=models.DateField(blank=True, help_text='Final collection date before subscription ends', null=True),
        ),
    ]
