# Generated by Django 5.2.7 on 2025-11-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_customer_subscription_cancelled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCustomer',
            fields=[
            ],
            options={
                'verbose_name': 'Business Customer',
                'verbose_name_plural': 'Business Customers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.customer',),
        ),
    ]
