# Generated by Django 5.2.7 on 2025-11-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_businesscustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='receiver_name',
            field=models.CharField(blank=True, help_text='Name of person receiving delivery (for businesses)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit/Office/Building number', max_length=100, null=True),
        ),
    ]
