# Generated by Django 5.2.7 on 2025-11-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_customer_phone_shippingaddress_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingparcel',
            name='estimated_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer's estimated weight in kg", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_reference',
            field=models.CharField(blank=True, default='', help_text='WTN reference number', max_length=50),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_signature',
            field=models.TextField(blank=True, default='', help_text='Base64 encoded signature image'),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_signed_date',
            field=models.DateTimeField(blank=True, help_text='Date WTN was signed', null=True),
        ),
    ]
