# Generated by Django 5.2.7 on 2025-11-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_incomingparcel_estimated_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingparcel',
            name='collection_scheduled_date',
            field=models.DateField(blank=True, help_text='Scheduled collection date for subscription customers', null=True),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_admin_approved',
            field=models.BooleanField(default=False, help_text='Admin has countersigned the WTN'),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_admin_approved_date',
            field=models.DateTimeField(blank=True, help_text='Date admin countersigned', null=True),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_admin_signature',
            field=models.TextField(blank=True, default='', help_text="Admin's base64 encoded signature"),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_pdf_path',
            field=models.CharField(blank=True, default='', help_text='Path to generated PDF WTN', max_length=500),
        ),
    ]
