# Generated by Django 5.2.7 on 2025-11-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_incomingparcel_collection_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_reminder_sent',
            field=models.BooleanField(default=False, help_text='Has the 3-day reminder email been sent?'),
        ),
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_reminder_sent_date',
            field=models.DateTimeField(blank=True, help_text='When the reminder was sent', null=True),
        ),
    ]
