# Generated by Django 5.2.7 on 2025-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_incomingparcel_wtn_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingparcel',
            name='wtn_admin_signature',
            field=models.TextField(blank=True, default='', help_text="Admin's base64 encoded signature"),
        ),
        migrations.AlterField(
            model_name='incomingparcel',
            name='wtn_signature',
            field=models.TextField(blank=True, default='', help_text='Base64 encoded signature image'),
        ),
    ]
