# Generated by Django 5.2.7 on 2025-11-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_incomingparcel_wtn_admin_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingparcel',
            name='wtn_admin_signature',
        ),
        migrations.RemoveField(
            model_name='incomingparcel',
            name='wtn_signature',
        ),
        migrations.AlterField(
            model_name='incomingparcel',
            name='wtn_admin_approved',
            field=models.BooleanField(default=False, help_text='Admin has approved the WTN'),
        ),
        migrations.AlterField(
            model_name='incomingparcel',
            name='wtn_admin_approved_date',
            field=models.DateTimeField(blank=True, help_text='Date admin approved', null=True),
        ),
    ]
