# Generated by Django 5.2.7 on 2025-11-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_remove_incomingparcel_wtn_admin_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sic_code',
            field=models.CharField(blank=True, help_text='Standard Industrial Classification code (optional)', max_length=10, null=True),
        ),
    ]
