# Generated by Django 5.2.7 on 2025-11-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_customer_sic_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_signature',
            field=models.TextField(blank=True, default='', help_text="Customer's base64 encoded signature image"),
        ),
    ]
