# Generated by Django 5.2.7 on 2025-11-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_incomingparcel_wtn_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingparcel',
            name='wtn_admin_signature',
            field=models.TextField(blank=True, default='', help_text="Admin's base64 encoded signature image"),
        ),
    ]
