# Generated by Django 5.2.7 on 2025-11-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_incomingparcel_wtn_admin_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Is this product currently on sale?'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_comment',
            field=models.CharField(blank=True, help_text="Optional sale description (e.g., 'Black Friday Deal', '20% Off')", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Sale price (only used if 'is on sale' is checked)", max_digits=7, null=True),
        ),
    ]
