# Generated by Django 5.2.7 on 2025-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image1',
            field=models.ImageField(blank=True, help_text='Review photo 1', null=True, upload_to='reviews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='image2',
            field=models.ImageField(blank=True, help_text='Review photo 2', null=True, upload_to='reviews/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='image3',
            field=models.ImageField(blank=True, help_text='Review photo 3', null=True, upload_to='reviews/%Y/%m/'),
        ),
    ]
