# Generated by Django 5.2.7 on 2025-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_productreview_image1_productreview_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name (e.g., 'Tier 1 subscription', 'Tier 1 early adopter')", max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in dropdowns (lower numbers first)')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Monthly subscription price', max_digits=6)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time setup fee', max_digits=6)),
                ('minimum_months', models.IntegerField(default=0, help_text='Minimum commitment in months (0 = cancel anytime)')),
                ('price_locked', models.BooleanField(default=False, help_text='Is pricing locked for life while subscribed?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this plan currently available for selection?')),
                ('description', models.TextField(blank=True, help_text='Internal notes about this plan')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EARNED', 'Earned from Parcel'), ('REDEEMED', 'Redeemed for Discount'), ('ADJUSTED', 'Manual Adjustment'), ('BONUS', 'Bonus Points'), ('Admin Addition', 'Admin Addition')], default='EARNED', max_length=20),
        ),
    ]
