# Generated by Django 5.2.7 on 2025-11-29 20:21

from django.db import migrations


def create_subscription_plans(apps, schema_editor):
    """Create initial subscription plans"""
    SubscriptionPlan = apps.get_model('store', 'SubscriptionPlan')
    
    plans = [
        {
            'name': 'Tier 1 subscription',
            'display_order': 1,
            'monthly_price': 30.00,
            'setup_fee': 30.00,
            'minimum_months': 0,
            'price_locked': False,
            'is_active': True,
        },
        {
            'name': 'Tier 2 subscription',
            'display_order': 2,
            'monthly_price': 27.50,
            'setup_fee': 0.00,
            'minimum_months': 3,
            'price_locked': False,
            'is_active': True,
        },
        {
            'name': 'Tier 1 early adopter',
            'display_order': 3,
            'monthly_price': 27.50,
            'setup_fee': 30.00,
            'minimum_months': 0,
            'price_locked': True,
            'is_active': True,
        },
        {
            'name': 'Tier 2 early adopter',
            'display_order': 4,
            'monthly_price': 25.00,
            'setup_fee': 0.00,
            'minimum_months': 3,
            'price_locked': True,
            'is_active': True,
        },
    ]
    
    for plan_data in plans:
        SubscriptionPlan.objects.create(**plan_data)


def reverse_subscription_plans(apps, schema_editor):
    """Remove subscription plans on rollback"""
    SubscriptionPlan = apps.get_model('store', 'SubscriptionPlan')
    SubscriptionPlan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.RunPython(create_subscription_plans, reverse_subscription_plans),
    ]
